kind: pipeline
name: default
type: docker

steps:
  - name: deploy
    image: docker.umputun.com/system/deploy-ci:master
    commands:
      - ssh umputun@remark42.com "cd /tmp && git clone git@github.com:umputun/remark-site.git --recurse-submodules remark42-site.git"
      - ssh umputun@remark42.com "cd /tmp/remark42-site.git && docker rm -f remark42-site || exit 0"
      - ssh umputun@remark42.com "cd /tmp/remark42-site.gi && docker-compose build && docker-compose up && docker-compose rm -f"
      - ssh umputun@remark42.com "rm -rf /srv/www/remark42.com/ && mkdir -p /srv/www/remark42.com && cp /tmp/remark42-site.git/public /srv/www/remark42.com && sudo rm -rf /tmp/remark42-site.git"
    when:
      branch: master
      event: push

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.mailgun.org
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: drone@mg.umputun.dev
      recipients: [sys@umputun.dev]
    when:
      status: [changed, failure]
